
name: Probar y crear 

on:
  push:
    branches: [ "main" ]
  
permissions:
  contents: read
  packages: write

jobs:
  test_and_build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Configurar entorno Python versión 3 
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: "3.12.10"
    # - name: Instalación de dependencias
    #   run: pip install -r src/libraries.txt
    # - name: Testeo con pytest
    #   working-directory: src
    #   run: pytest test-calculadora.py 
    # - name: Linteo
    #   working-directory: src
    #   run: ruff check .
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    # - name: Build and push
    - name: Imagen docker para testeo
      uses: docker/build-push-action@v6
      with:
          context: .
          # push: true
          load: true
          tags: ghcr.io/igneer/ci-cd_contenedores:test
    - name: Ejecutar test en el contenedor
      run: | 
        docker run --rm ghcr.io/igneer/ci-cd_contenedores:test pytest test-calculadora.py && docker run --rm ghcr.io/igneer/ci-cd_contenedores:test ruff check test-calculadora.py

    - name: Build and Push Final Image
      uses: docker/build-push-action@v6
      with:
          context: .
          push: true
          tags: ghcr.io/igneer/ci-cd_contenedores:latest