
name: Probar y crear 

on:
  push:
    branches: [ "main" ]
  
permissions:
  contents: read

jobs:
  test_and_build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configurar entorno Python versión 3 
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.10"
    - name: Instalación de dependencias
      run: pip install -r src/libraries.txt
    - name: Testeo con pytest
      working-directory: src
      run: pytest test-calculadora.py 
